var eomj = {
  file:[
      "heihei.png", "haha.png", "daxiao.png", "xixi.png", "biyanxiao.png", "kuxiao.png", "xiaoku.png", "xiaodedagun.png",
      "weixiao.png", "xiuseweixiao.png", "hehe.png", "daolian.png", "shiran.png", "huachi.png", "feiwen.png", "haochi.png",
      "tushe.png", "danyantushe.png", "guilian.png", "tiaomei.png", "daidanpianyanjingdelian.png", "shudaizi.png", "mojingxiaolian.png", "xingxingyan.png",
      "deyi.png", "bugaoxing.png", "shiwang.png", "bukaixin.png", "danxin.png", "kunrao.png", "weiweibuman.png", "buman.png",
      "tongku.png", "kunhuo.png", "zhuakuang.png", "pijuan.png", "ku.png", "daku.png", "shengqi.png", "nuhuozhongshao.png",
      "zuishangyoufuhaodelian.png", "baozhatou.png", "zhengdashuangyan.png", "kongju.png", "haipa.png", "lenghan.png", "shiwangdanrushizhongfu.png", "han.png",
      "baobao.png", "xiangyixiang.png", "wuzui.png", "anjing.png", "shuohuang.png", "chenmo.png", "lengmo.png", "wuyu.png",
      "ziyaliezui.png", "fanbaiyan.png", "kunao.png", "chijing.png", "zhenjing.png", "shuizhaole.png", "liukoushui.png", "kun.png",
      "touyunmuxuan.png", "bizui.png", "exin.png", "outu.png", "ganmao.png", "fashao.png", "facai.png", "niuzailian.png",
      "shengqideemo.png", "dabian.png", "kulou.png", "zhangkaishuangshou.png", "jushuangshou.png", "guzhang.png", "woshou.png", "muzhixiangshang.png",
      "muzhixiangxia.png", "chuquan.png", "juqiquantou.png", "chaozuodequantou.png", "chaoyoudequantou.png", "shengli.png", "aini.png", "ok.png",
      "xiangzuozhi.png", "xiangyouzhi.png", "xiangshangzhi.png", "xiangxiazhi.png", "jirou.png", "shuangshouheshi.png", "jiaoyin.png", "nvshijinzhishoushi.png",
      "nanshijinzhishoushi.png", "nvshijushou.png", "nanshijushou.png", "nvshiwulian.png", "nanshiwulian.png", "nvshisongjian.png", "nanshisongjian.png", "nvshijugong.png",
      "nanshijugong.png", "huashu.png", "meigui.png", "yinghua.png", "kuwei.png", "pengzhuang.png", "hongxin.png", "xingxing.png",
      "pengbei.png", "ganbei.png", "jiangpai.png", "jiangbei.png", "yaowan.png", "bianpao.png", "caidao.png", "qian.png",
      "gouwuche.png", "huoche.png", "naozhong.png", "wucaizhixie.png", "lapaocaidai.png", "shu.png", "qianbi.png", "shibajin.png",
      "xiangling.png", "jinzhixiangling.png", "kuoyinqi.png", "guoqi.png"
  ],
  text:[
      "[嘿嘿]", "[哈哈]", "[大笑]", "[嘻嘻]", "[闭眼笑]", "[苦笑]", "[笑哭]", "[笑得打滚]",
      "[微笑]", "[羞涩微笑]", "[呵呵]", "[倒脸]", "[释然]", "[花痴]", "[飞吻]", "[好吃]",
      "[吐舌]", "[单眼吐舌]", "[鬼脸]", "[挑眉]", "[戴单片眼镜的脸]", "[书呆子]", "[墨镜笑脸]", "[星星眼]",
      "[得意]", "[不高兴]", "[失望]", "[不开心]", "[担心]", "[困扰]", "[微微不满]", "[不满]",
      "[痛苦]", "[困惑]", "[抓狂]", "[疲倦]", "[哭]", "[大哭]", "[生气]", "[怒火中烧]",
      "[嘴上有符号的脸]", "[爆炸头]", "[睁大双眼]", "[恐惧]", "[害怕]", "[冷汗]", "[失望但如释重负]", "[汗]",
      "[抱抱]", "[想一想]", "[捂嘴]", "[安静]", "[说谎]", "[沉默]", "[冷漠]", "[无语]",
      "[龇牙咧嘴]", "[翻白眼]", "[苦恼]", "[吃惊]", "[震惊]", "[睡着了]", "[流口水]", "[困]",
      "[头晕目眩]", "[闭嘴]", "[恶心]", "[呕吐]", "[感冒]", "[发烧]", "[发财]", "[牛仔脸]",
      "[生气的恶魔]", "[大便]", "[骷髅]", "[张开双手]", "[举双手]", "[鼓掌]", "[握手]", "[拇指向上]",
      "[拇指向下]", "[出拳]", "[举起拳头]", "[朝左的拳头]", "[朝右的拳头]", "[胜利]", "[爱你]", "[ok]",
      "[向左指]", "[向右指]", "[向上指]", "[向下指]", "[肌肉]", "[双手合十]", "[脚印]", "[女士禁止手势]",
      "[男士禁止手势]", "[女士举手]", "[男士举手]", "[女士捂脸]", "[男士捂脸]", "[女士耸肩]", "[男士耸肩]", "[女士鞠躬]",
      "[男士鞠躬]", "[花束]", "[玫瑰]", "[樱花]", "[枯萎]", "[碰撞]", "[红心]", "[星星]",
      "[碰杯]", "[干杯]", "[奖牌]", "[奖杯]", "[药丸]", "[鞭炮]", "[菜刀]", "[钱]",
      "[购物车]", "[货车]", "[闹钟]", "[五彩纸屑]", "[拉炮彩带]", "[书]", "[铅笔]", "[18禁]",
      "[响铃]", "[禁止响铃]", "[扩音器]", "[国旗]"
  ],
};
