//全局配置信息，由运维负责维护
module.exports = {
    site:{
        "help":'http://neibuhelp.kongfz.com/',
        "book":'http://neibubook.kongfz.com/',
        "cart":'http://neibucart.kongfz.com/',
        "carts":'https://neibucart.kongfz.com/',
        "davUpload":"http://image-upload.kfz.com/",
        "gateway":"http://neibugateway.kongfz.com/",
        "gujiushu":" http://neibuwww.gujiushu.com/",
        "xinyu":"http://neibuxinyu.kongfz.com/",
        "shop":"http://neibushop.kongfz.com/",
        "mbook":'http://neibumbook.kongfz.com/',
        "item":'http://neibuitem.kongfz.com/',
        "login":"https://neibulogin.kongfz.com/",
        "message":"http://neibumessage.kongfz.com/",
        "m":"https://neibum.kongfz.com/",
        "mmessage":"http://neibummessage.kongfz.com/",
        "mpm":"http://neibum.kongfz.cn/",
        "operation":'http://neibuoperation.kongfz.com/',
        "pay":" https://neibupay.kongfz.com/",
        "pcgateway":"http://neibupc-gateway.kongfz.com/",
        "pmgs":" http://neibupmgs.kongfz.com/",
        "pm":"http://neibuwww.kongfz.cn/",
        "search":'http://neibusearch.kongfz.com/',
        "searchs":'https://neibusearch.kongfz.com/',
        "service":" http://neibuservice.kongfz.com/",
        "tan":" http://neibutan.kongfz.com/",
        "user":"http://neibuuser.kongfz.com/",
        "users":"https://neibuuser.kongfz.com/",
        "wechat":"https://neibuwechat.kongfz.com/",
        "www":'http://neibuwww.kongfz.com/',
        "wwws":'https://neibuwww.kongfz.com/',
        "zixun":" http://neibuzixun.kongfz.com/",
        "subs": "wss://neibusub.kongfz.cn/",
        "app": "http://neibuapp.kongfz.com/",
        "cn_subs": "wss://neibusub.kongfz.cn/",
        "cn_message":"http://neibumessage.kongfz.cn/",
        "cn_cart": "http://neibucart.kongfz.cn/",
        "s_cn_cart": "https://neibucart.kongfz.cn/",
    }
}